name: Daily Hydration Reminder to Team

on:
  schedule:
    - cron: '0 10 * * *'  # 10:00 AM UTC every day
  workflow_dispatch:

jobs:
  hydration-reminder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Send hydration message to Slack
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.STAY_HYDRATED }}
        run: |
          MESSAGE=$(cat .github/hydration-message.txt | sed ':a;N;$!ba;s/\n/\\n/g')
          JSON="{\"text\":\"$MESSAGE\"}"

          curl -X POST -H "Content-type: application/json" \
            --data "$JSON" \
            "$SLACK_WEBHOOK_URL"
