name: Daily Hydration Reminder to Team

on:
  schedule:
    - cron: '0 10 * * *'  # Every day at 10:00 AM UTC
  workflow_dispatch:   # Allow manual trigger

jobs:
  hydration-reminder:
    runs-on: ubuntu-latest

    steps:
      - name: Send Hydration Reminder to Slack
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.STAY_HYDRATED }}
        run: |
          MESSAGE="💧 *Time for a Water Break!*\n\
Could you please take a sip of water?\n\
Your body might be getting dehydrated.\n\
Stay hydrated to keep your energy up and your focus sharp — let’s work seamlessly and stay refreshed! 💪"

          curl -X POST -H 'Content-type: application/json' \
            --data "{\"text\":\"$MESSAGE\"}" \
            "$SLACK_WEBHOOK_URL"
