
name: Daily Hydration Reminder to Team

on:
  schedule:
    - cron: '* * * * *'  # Every minute
  workflow_dispatch:

jobs:
  hydration-reminder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Read Message and Send to Slack
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.STAY_HYDRATED }}
        run: |
          MESSAGE=$(cat .github/hydration-message.txt)
          JSON="{\"text\":\"$MESSAGE\"}"
          curl -X POST -H "Content-type: application/json" \
            --data "$JSON" \
            "$SLACK_WEBHOOK_URL"
