name: Daily Hydration Reminder to Team

on:
  schedule:
    - cron: '0 10 * * *'  # Every day at 10:00 AM UTC
  workflow_dispatch:

jobs:
  hydration-reminder:
    runs-on: ubuntu-latest

    steps:
      - name: Send Hydration Reminder to Slack
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.STAY_HYDRATED }}
        run: |
          MESSAGE="💧 *Time for a Water Break!*\nCould you please take a sip of water?\nYour body might be getting dehydrated.\nStay hydrated to keep your energy up and your focus sharp — let’s work seamlessly and stay refreshed! 💪"
          JSON_PAYLOAD=$(printf '{"text":"%s"}' "$MESSAGE")

          curl -X POST -H 'Content-type: application/json' \
            --data "$JSON_PAYLOAD" \
            "$SLACK_WEBHOOK_URL"
