name: Daily Hydration Reminder to Team

on:
  schedule:
    - cron: '* * * * *'  # Runs every minute
  workflow_dispatch:     # Manual trigger

jobs:
  hydration-reminder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Read Message and Send to Slack
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.STAY_HYDRATED }}
        run: |
          # Read the hydration message from the file and escape newlines
          MESSAGE=$(cat .github/hydration-message.txt | sed ':a;N;$!ba;s/\n/\\n/g')
          
          # Prepare the JSON payload
          JSON="{\"text\":\"$MESSAGE\"}"

          # Send the message to Slack using the webhook
          curl -X POST -H "Content-type: application/json" \
            --data "$JSON" \
            "$SLACK_WEBHOOK_URL"
